
export const SET_IS_LANDSCAPE = 'SET_IS_LANDSCAPE';
export const START_GAME = 'START_GAME';
export const SET_GAME_STATUS = 'SET_GAME_STATUS';
export const TURN_ENDED = 'TURN_ENDED';
export const OPPONENT_TURN_ENDED = 'OPPONENT_TURN_ENDED';
export const SUMMONED = 'SUMMONED';
export const OPPONENT_SUMMONED = 'OPPONENT_SUMMONED';
export const ATTACKED = 'ATTACKED';
export const OPPONENT_ATTACKED = 'OPPONENT_ATTACKED';
export const TRAP_SET = 'TRAP_SET';
export const OPPONENT_TRAP_SET = 'OPPONENT_TRAP_SET';
export const SET_SELECTED_CARD = 'SET_SELECTED_CARD';
export const SET_SHOW_MODAL = 'SET_SHOW_MODAL';
